spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easyops
    username: easyops
    password: easyops123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: hr
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false


