spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/easyops
    username: easyops
    password: easyops123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.easyops: DEBUG

